version: '3.8'
volumes:
  db-data:
    driver: local
services:
    web:
        image: nginx:latest
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        image: php:8.0.9-fpm
        depends_on:
            - database
        volumes:
            - ./:/var/www
        environment:
            APP_ENV: dev
            MERCURE_PUBLISH_URL: http://mercure/.well-known/mercure
    
    database:
        image: 'mysql:latest'
        environment:
            MYSQL_DATABASE: main
            MYSQL_USER: admin
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
        ports:
            - '3306'
        volumes:
            - db-data:/var/lib/mysql

    phpmyadmin:
        depends_on: 
            - database
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: root

    mercure:
        restart: unless-stopped
        image: dunglas/mercure:v0.10.4
        environment:
            - PUBLISHER_JWT_KEY=mercure_publisher
            - SUBSCRIBER_JWT_KEY=mercure_subscriber
            - CORS_ALLOWED_ORIGINS=*
            - PUBLISH_ALLOWED_ORIGINS=*
            - ALLOW_ANONYMOUS=1
            - MERCURE_EXTRA_DIRECTIVES=cors_allowed_origins *
        ports:
            - 8001:80